### ISSUE TITLE
test_fast_inla[jax] is failing for me on M1

### ISSUE THREAD

**Issue by tbenthompson** [Confirm-Solutions/imprint#121]
@constinit 

I suspect this is architecture related since the CI for this test is consistently passing. The problem was introduced during one of the recent numerical stability/optimization PRs. I'm just documenting this here and not fixing it because it seems like it might be a tough one to resolve. 

```
research/berry/berrylib/test_berry.py:184: in test_fast_inla
    np.testing.assert_allclose(out[0][0].sum(), 2111.808, rtol=1e-3)
E   AssertionError: 
E   Not equal to tolerance rtol=0.001, atol=0
E   
E   Mismatched elements: 1 / 1 (100%)
E   Max absolute difference: 50.70225391
E   Max relative difference: 0.02400893
E    x: array(2162.5103, dtype=float32)
E    y: array(2111.808)
```

**Comment by constinit** [comment]
Good find. This is now passing on my M1:
https://github.com/Confirm-Solutions/imprint/pull/113
