### ISSUE TITLE
Improve CI pipeline speed

### ISSUE THREAD

**Issue by constinit** [Confirm-Solutions/imprint#84]
The CI pipeline currently takes [~5 minutes](https://github.com/mikesklar/kevlar/actions/runs/2192273998) just to lint.

We should consider configuring the [actions cache](https://dev.to/epassaro/caching-anaconda-environments-in-github-actions-5hdex) or, if necessary, building a [docker image](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action) with everything ready to go.

@tbenthompson

**Comment by tbenthompson** [comment]
Closed by https://github.com/Confirm-Solutions/imprint/pull/107
